// <auto-generated />
using LearnEngine.Infrastucture.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnEngine.Infrastucture.Migrations
{
    [DbContext(typeof(LearnEngineDbContext))]
    [Migration("20211115155538_manytomanytest1")]
    partial class manytomanytest1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LearnEngine.Core.Entities.SQL.Node", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("MaterialTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("NodeNode", b =>
                {
                    b.Property<string>("ParentNodesId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubNodesId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ParentNodesId", "SubNodesId");

                    b.HasIndex("SubNodesId");

                    b.ToTable("NodeNode");
                });

            modelBuilder.Entity("NodeNode", b =>
                {
                    b.HasOne("LearnEngine.Core.Entities.SQL.Node", null)
                        .WithMany()
                        .HasForeignKey("ParentNodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnEngine.Core.Entities.SQL.Node", null)
                        .WithMany()
                        .HasForeignKey("SubNodesId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
