// <auto-generated />
using LearnEngine.Infrastucture.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnEngine.Infrastucture.Migrations
{
    [DbContext(typeof(LearnEngineDbContext))]
    [Migration("20211115152313_pk_test")]
    partial class pk_test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LearnEngine.Core.Entities.SQL.Node", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("MaterialTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("LearnEngine.Core.Entities.SQL.Node", b =>
                {
                    b.HasOne("LearnEngine.Core.Entities.SQL.Node", "ParentNode")
                        .WithMany("SubNodes")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("LearnEngine.Core.Entities.SQL.Node", b =>
                {
                    b.Navigation("SubNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
